name: 'Readme i18n Switcher'
description: 'Automatically generate a language switcher table in README.md based on translated README.*.md files. Without `git push`.'
author: 'n9gc'

inputs:
    folders:
        description: |
            Folders of READMEs, one line each
        default: '.'
        required: false
    fileName:
        description: |
            The pattern of readme files' name, where `{lang}` is used to match the locale of the readme.
            RFC 6570.
        default: 'README.{lang}.md'
        required: false
    repoReadme:
        description: |
            The readme file that will be displayed as repo's README.
            If not provided, repo's README will not be changed.
        default: ''
        required: false
    tag:
        description: |
            A piece of text that will be replaced by generated switcher
        default: '<!-- auto-readme-i18n-switcher-->'
        required: false
    switcherBody:
        description: |
            Template string for the outter of switcher.
            micromustache.

            all vars:
            - `lines` the inner text of the switcher
        default: '| {{lines}} |'
        required: false
    switcherLine:
        description: |
            Template string for each language option of switcher.
            micromustache.

            all vars:
            - `display` the localed language option to display
            - `filePath` the path of the readme
            - `folder` the folder of the readme
            - `lang` the text inside `{lang}` of the readme file
        default: '[{{display}}]({{path}})'
        required: false
    switcherLineActive:
        description: |
            Template string for the language option of the readme now.
            micromustache.

            all vars:
            - `display` the localed language option to display
            - `filePath` the path of the readme
            - `folder` the folder of the readme
            - `lang` the text inside `{lang}` of the readme file
        default: '{{display}}'
        required: false
    switcherSpliter:
        description: |
            Text used to separate each language option of the switcher
        default: ' | '
        required: false

runs:
    using: 'node24'
    main: 'dist.js'
